### ISSUE TITLE
Dashboard Authorization: Guest

### ISSUE THREAD

**Issue by meyerhoferc** [janderson16/CloneBnB#1]
As a guest,
when I go to /dashboard
I am redirected to the login page.

**Comment by AliSchlereth** [comment]
@janderson16 When I visit the /dashboard it renders a 404 instead of redirecting to the login page. As the client I am okay with this behavior but want to check since it doesn't quite match the user story.

**Comment by janderson16** [comment]
restyled 404

**Comment by AliSchlereth** [comment]
Check!
