### ISSUE TITLE
Host Dashboard: Messages

### ISSUE THREAD

**Issue by meyerhoferc** [janderson16/CloneBnB#11]
As a host user,
when I go to /dashboard
and when I click on 'messages'
I'm taken to /messages
and I see a list of all of my conversations
and I click on a conversation
then I see all of the messages between me and the other person
and I can enter a message into a text box
and click send
and the message is sent to the other person

**Comment by meyerhoferc** [comment]
Will this be the host's reservations they've logged as a traveler user or the reservations made for their listings?

**Comment by AliSchlereth** [comment]
Check!
