### ISSUE TITLE
Host Dashboard: Edit Profile

### ISSUE THREAD

**Issue by meyerhoferc** [janderson16/CloneBnB#13]
As a host user,
when I go to /dashboard
and when I click 'edit profile'
I'm taken to a form
and I can edit my profile
and click "Update Profile"
and I'm at my dashboard
and my information is updated

**Comment by janderson16** [comment]
same issue as card 5, can see other users data by changing url

**Comment by AliSchlereth** [comment]
Looks like the URL changes but the edit view and update are tied to me as a signed in user so I'm signing off on this.
