### ISSUE TITLE
Nav Bar: Become a host (as a guest)

### ISSUE THREAD

**Issue by valerietrudell** [janderson16/CloneBnB#20]
A guest visits the root page, they see a button on the nav bar - Become a host they are directed to a [login or signup] page. They don't have an account so they click signup and fill out: 
-first_name
					-last_name  
					-email  
					-phone number
					-password
					-confirmation password  
They click create account and have made an account. They are directed to the edit profile page and fill out: 
					- about_me
					- use_photo is uploaded 
They click submit and are directed to the new listing page where they fill out: 
					- street address
					- city
					- state
					- zip 
					- description
					- max occupancy 
					- listing type
					- bed layout
					- title of listing
					- images of listing 
They click create listing are directed directed to user dashboard. They are given role of host, has a user_id and a host_id

**Comment by janderson16** [comment]
'Become a Host' button only shows after signing in

**Comment by meyerhoferc** [comment]
accepted due to stylistic changes

**Comment by AliSchlereth** [comment]
There are some significant changes from this flow. I'm okay accepting this card since it seems like all the pieces are covered in other cards. @janderson16 as PM you might want to double check that nothing falls through the cracks here.
