### ISSUE TITLE
Navbar: Become a host (as a traveler not signed in)

### ISSUE THREAD

**Issue by valerietrudell** [janderson16/CloneBnB#21]
A guest visits the root page, they see a button on the nav bar - Become a host they are directed to a [signup or login page]  
They are directed to the login page, they put in email and password and click submit, they are directed to the new listing page and fill out: 
					- street address
					- city
					- state
					- zip 
					- description
					- max occupancy 
					- listing type
					- bed layout
					- title of listing
					- images of listing 
They click create listing and they are directed the the user dashboard

**Comment by janderson16** [comment]
directed to dashboard not new_listing_path

**Comment by meyerhoferc** [comment]
I think we talked about having this direct to dashboard and then there's a button for making a new listing, @pixapi is working on that

**Comment by meyerhoferc** [comment]
accepted due to stylistic changes. a host can create a listing from their dashboard
