### ISSUE TITLE
Navbar: Become a host (as a traveler signed in)

### ISSUE THREAD

**Issue by valerietrudell** [janderson16/CloneBnB#22]
A traveler visits the root page, they see a button on the nav bar - Become a host they are directed to a  to the new listing page and fill out:
- street address
- city
- state
- zip
- description
- max occupancy
- listing type
- bed layout
- title of listing
- images of listing
They click create listing and they are directed the the user dashboard

**Comment by janderson16** [comment]
'Become Host' is directed to edit profile; 'Update Profile' adds host role but not sent to new listing path

**Comment by meyerhoferc** [comment]
accepted due to stylistic changes

**Comment by AliSchlereth** [comment]
Looks like the create new listing is covered in either card 56 or 35.
