### ISSUE TITLE
Navbar: Sign-up (travelers)

### ISSUE THREAD

**Issue by valerietrudell** [janderson16/CloneBnB#23]
A guest visit the root page, they see a button on the nav bar - Sign Up -  
		They are directed to the signup page and fill out: 
					-first_name
					-last_name  
					-email  
					-password
					-confirmation password  
 					-click create account 
			- from signup they are directed to a edit profile page where they fill out: 
					- about_me
					- use_photo is uploaded 
					- click submit 
		They are directed to the user dashboard

**Comment by AliSchlereth** [comment]
I could sign up! Looks good to me.
