### ISSUE TITLE
Booking: making reservation (as a traveler)

### ISSUE THREAD

**Issue by pixapi** [janderson16/CloneBnB#25]
As a logged in user (traveler)
when I visit booking path
and I click on the calendar for starting date
and I click on the calendar for ending date
I can see the total price for the stay
I can see the selected dates
I click on Book button
and I get redirected to confirmation path
and the listing is no longer available for those dates

**Comment by AliSchlereth** [comment]
@meyerhoferc This functionality looks pretty good. I'd like the flash message from when someone tries to double book a date to be a bit more obvious (i.e. color, placement, etc). Also, it would be nice for the confirmation page to show the title of the listing. Right now I think maybe it lists just the location(?).

**Comment by meyerhoferc** [comment]
title of listing now updated, still needs styling

**Comment by AliSchlereth** [comment]
Check!
