### ISSUE TITLE
Navbar: links available (as a guest)

### ISSUE THREAD

**Issue by pixapi** [janderson16/CloneBnB#29]
As a non registered user (guest)
when I visit root (‘/‘)
I can see on the nav bar Become a Host button
I can see on the nav bar Sign up
I can see on the nav bar Login

**Comment by janderson16** [comment]
missing 'Become a Host' button

**Comment by meyerhoferc** [comment]
For how this is set up right now, a user can only become a host when they already have an account. If you like, the become a host button can take them to create an account @janderson16

**Comment by AliSchlereth** [comment]
With @meyerhoferc's update this looks to be implemented.
