### ISSUE TITLE
Become a host: register as a host

### ISSUE THREAD

**Issue by pixapi** [janderson16/CloneBnB#34]
As a registered user
when I visit ‘/‘
and I'm logged in
and click Become a host button
I get redirected to a confirmation page
I click on Sign Up as a Host
I get redirected to dashboard path
and I see a link to Create a New Listing

**Comment by janderson16** [comment]
'My Listings' button on sidebar redirects to all listings (linstings_index_path)

**Comment by meyerhoferc** [comment]
This has been fixed with my most recent PR

**Comment by AliSchlereth** [comment]
Check!
