### ISSUE TITLE
Host Reservations: Update Status

### ISSUE THREAD

**Issue by meyerhoferc** [janderson16/CloneBnB#74]
As a logged in host,
when I visit /dashboard
and I click on "Reservations"
I can see the status of a reservation
and I can mark it as confirmed
and the reservation's status is marked as confirmed
and I can mark it as cancelled
and the reservation's status is marked as cancelled
and I can mark it as completed
and the reservation's status is marked as completed

**Comment by AliSchlereth** [comment]
@meyerhoferc @janderson16
I can't make a listing live. Is there a host that has been populated through seed that I could log in as to check this functionality?

**Comment by AliSchlereth** [comment]
Check!
